create table if not exists cash_sessions (
  id bigint generated by default as identity primary key,
  date date not null,
  starting_cash numeric(12, 2) not null check (starting_cash >= 0),
  expected_cash numeric(12, 2) not null default 0 check (expected_cash >= 0),
  actual_cash numeric(12, 2),
  discrepancy numeric(12, 2),
  created_at timestamptz not null default now(),
  unique (date)
);

create table if not exists sales (
  id bigint generated by default as identity primary key,
  session_id bigint not null references cash_sessions(id) on delete cascade,
  amount numeric(12, 2) not null check (amount >= 0),
  description text,
  created_at timestamptz not null default now()
);

create table if not exists expenses (
  id bigint generated by default as identity primary key,
  session_id bigint not null references cash_sessions(id) on delete cascade,
  amount numeric(12, 2) not null check (amount >= 0),
  reason text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_sales_session_id_created_at
  on sales (session_id, created_at desc);

create index if not exists idx_expenses_session_id_created_at
  on expenses (session_id, created_at desc);
